# Config strings
blockbuster.config:
    general:
        title: 通用

        show_first_time_modal: 顯示第一次使用提示
        disable_teleport_playback_button: 關閉播放後瞬移功能
        extra_wubs: 附加的雜物
        auto_refresh_models: 刷新模型和皮膚
        debug_playback_ticks: Debug ticks
        green_screen_sky: 色鍵天空
        green_screen_sky_color: 色鍵天空顏色
        url_skins_sync_download: 同步的 URL 下載
        
    model_block:
        title: 模型方塊
        
        model_block_disable_rendering: 關閉模型方塊渲染
        model_block_disable_item_rendering: 關閉背包內渲染

    recording:
        title: 錄制

        recording_countdown: 錄制倒計時
        recording_delay: 錄制跳過幀
        record_unload_time: 自動解除安裝錄制的時間
        record_unload: 自動解除安裝錄制的
        record_sync_rate: 錄制 tick 的同步率
        record_attack_on_swipe: 揮動手攻擊
        record_commands: 錄制命令
        record_chat_prefix: 聊天動作的前置代號

    actor:
        title: 演員

        actor_fall_damage: 演員掉落傷害
        actor_tracking_range: 演員跟蹤範圍
        actor_rendering_range: 演員渲染範圍
        actor_always_render: 總是渲染演員
        actor_always_render_names: 總是渲染演員的名稱
        actor_swish_swipe: 手臂劃動刷刷聲
        actor_y: 修復 Y 軸的運動

    damage_control:
        title: 傷害控制

        damage_control: 傷害控制
        damage_control_distance: 傷害距離
