# Config strings
blockbuster.config:
    title: Blockbuster

    general:
        title: 常規
        tooltip: Blockbuster mod 的常規選項

        show_first_time_modal: 展示首次使用提示
        extra_wubs: 附加的雜物
        auto_refresh_models: 刷新模型和皮膚
        debug_playback_ticks: 調試 Ticks
        green_screen_sky: 色度天空
        green_screen_sky_color: 色度天空顏色
        url_skins_sync_download: 同步的 URL 下載
        add_utility_blocks: 添加實用方塊
        cached_structure_rendering: 緩存結構渲染
        bb_gun_sync_distance: BB 槍距離同步
        
    model_block:
        title: 模型方塊
        tooltip: 與模型方塊相關的選項
        
        model_block_disable_rendering: 禁用模型方塊渲染
        model_block_disable_item_rendering: 禁用物品欄渲染
        restore: 恢復模型方塊
        reset_on_playback: 回放時重置

    recording:
        title: 錄制與回放
        tooltip: 所有與玩家回放系統相關的選項

        recording_countdown: 錄制倒計時
        record_unload_time: 自動卸載錄制的時間
        record_unload: 自動卸載錄制
        record_sync_rate: 錄制 Tick 的同步率
        record_attack_on_swipe: 揮手攻擊
        record_commands: 錄制命令
        record_chat_prefix: 聊天動作前綴
        record_pause_preview: 更好的預覽

    scenes:
        title: 場景
        tooltip: 所有與場景相關的選項 

        save_update: 保存後更新場景

    actor:
        title: 演員
        tooltip: 演員實體配置選項（與假玩家無關）

        actor_fall_damage: 演員跌落傷害
        actor_tracking_range: 演員跟蹤範圍
        actor_rendering_range: 演員渲染範圍
        actor_always_render: 始終渲染演員
        actor_always_render_names: 始終渲染演員的名稱
        actor_swish_swipe: 手臂劃動刷刷聲
        actor_y: 修復 Y 軸運動
        actor_disable_riding: 禁用騎乘
        actor_playback_body_yaw: 回放身體偏航

    damage_control:
        title: 破壞控制
        tooltip: 破壞控制是指在演員被錄制或場景完成回放後，恢復方塊的系統

        damage_control: 破壞控制
        damage_control_distance: 破壞距離

    model_folders:
        title: 模型文件夾
        tooltip: 添加附加的模型文件夾

        path: 附加文件夾

    snowstorm:
        title: Snowstorm
        tooltip: Snowstorm 是壹個可以創建相當復雜的粒子的例子系統，在這裏妳可以找到與該粒子系統相關的全局選項

        depth_sorting: 粒子按深度排序

    audio:
        title: 音頻
        tooltip: 遊戲內音頻同步功能相關的選項

        waveform_visible: 音頻條可見
        waveform_density: 波形密度
        waveform_width: 音頻條寬度
        waveform_height: 音頻條高度
        waveform_filename: 顯示音頻條的文件名