blockbuster.config.comments:
    general:
        show_first_time_modal: Чи потрібно відображати першоразове вітання на головній панелі
        extra_wubs: Ця опція буквально нічого не робить. А може й робить...? # та йоб твою мать
        auto_refresh_models: Оновлювати моделі та скіни при вході в інтерфейс Metamorph або Blockbuster?
        debug_playback_ticks: Записувати тіки в логи під час відтворення сцени
        green_screen_sky: Робить небо суцільного кольору для хромакеїнгу. Може не працювати з шейдерами!
        green_screen_sky_color: Вказує колір неба для функції хроманеба
        url_skins_sync_download: Синхронне завантаження URL-скінів. Таким чином можна використовувати URL-скінів з тривимірними зовнішніми шарами за ціною фризу гри для завантаження скінів
        add_utility_blocks: Додайте такі блоки, як блоки команд і структур, до вкладку творчого режиму у Blockbuster, аби спростити доступ до цих елементів
        bb_gun_sync_distance: Якщо значення більше 0, дане налаштування вмикає синхронізацію снарядів BB-Ґану, що забезпечує синхронізацію снарядів з сервером за рахунок мигтячої телепортації

    model_block:
        model_block_disable_rendering: Чи потрібно відображати блоки-моделі
        model_block_disable_item_rendering: Чи слід вимкнути рендеринг предметів у блоках-моделях (кому це потрібно?)
        model_block_missing_name_rendering: Відображати шлях моделей, у разі якщо вони відсутні. У режимі F3 вони відображатимуться завжди.
        model_block_debug_rendering_f1: Відображати куб для дебагінгу перебуваючи в режимі F1 паралельно з режимом дебагінгу F3.
        restore: Ця опція дозволяє повернути старий баг, що дозволяв відновити випадково знесені блоки-моделі.
        reset_on_playback: Якщо увімкнено, після початку відтворення сцени всі блоки-моделі скинуться

    recording:
        recording_countdown: Зворотний відлік запису (у секундах)
        record_unload_time: Скільки часу займе вивантаження запису (в тіках)
        record_unload: Увімкнути автоматичне вивантаження записів?
        record_sync_rate: Як часто запис синхронізуватиметься з сервером?
        record_attack_on_swipe: Чи записується дія атаки разом з дією змаху?
        record_commands: Чи записується дія команди під час запису?
        record_chat_prefix: Префікс, який буде додано до повідомлення в чаті (для імені поточного актора використовуйте шаблон %%NAME%%)
        record_pause_preview: Дана опція вмикає попередній перегляд анімованих морфів, таких як анімації морфів-світлин, анімованих поз, морфів-записів і секвенсорів. Дне налаштування впливає на продуктивність зі сторони серверу.
        record_render_debug_paths: Увімкнути відображення запису шляхів при дебагінгу.

    scenes:
        save_update: Чи потрібно перезавантажувати сцени, у разі якщо вони запущені, після збереження сцени шляхом виходу з графічного інтерфейсу головної панелі.

    actor:
        actor_fall_damage: Чи отримують актори пошкодження при падінні?
        actor_tracking_range: Як далеко відстежуються актори? Потребує перезапуску гри.
        actor_rendering_range: Як далеко видно акторів?
        actor_always_render: Зробити так, щоб актор завжди відображався, незалежно від того, де він знаходиться або розміру його хітбоксу
        actor_always_render_names: Увімкнути безумовне відображення тегів-назв акторів
        actor_swish_swipe: Чи видають актори звук, коли роблять змах?
        actor_y: Змушує акторів використовувати правильне значення Y (виправляє проблему з наведенням і стрибками, але робить рух по Y різким)
        actor_disable_riding: Вимкніть можливість їздити верхи на акторі, клацнувши його правою кнопкою миші
        actor_playback_body_yaw: Чи потрібно відтворювати окремо записане горизонтальне обертання тіла актора (гарантує послідовне обертання тіла так, як воно було записано, опція працює тільки на нових записах, записаних на Blockbuster 2.1+)

    damage_control:
        damage_control: Чи ввімкнено контроль пошкоджень
        damage_control_distance: Радіус дії контролю пошкоджень
        damage_control_message: Відображає попередження, якщо блоком, на який ви навелись, керує контроль пошкоджень

    model_folders:
        path: Абсолютний шлях до додаткової папки моделі (додайте букву диска якщо маєте ОС Windows)

    snowstorm:
        depth_sorting: У разі якщо увімкнено, виправляє частинки, які видно за іншими напівпрозорими частинками. Даний параметр є дуже ресурсоємним, використовуйте його лише під час рендерингу відеоматеріалів

    audio:
        waveform_visible: Чи потрібно показувати аудіосмуги під час відтворення
        waveform_density: Скільки пікселів аудіохвилі має бути показано за секунду
        waveform_width: Ширина аудіосмуги у відсотках з плаваючою комою (від 0 до 1)
        waveform_height: Висота аудіосмуги в пікселях
        waveform_filename: Чи потрібно показувати ім'я файлу відтворюваного аудіо
        waveform_time: Чи відображати таймер відтворення звукової доріжки. Майте на увазі, що таймер відтворення звукової доріжки може не відображати поточний час відтворення сцени!
        audio_sync: Чи потрібно завжди намагатися синхронізувати аудіо між сервером і клієнтом. Налаштування не впливає на відтворення та синхронізацію при повторному підключенні до сервера з запущеним аудіо. Даний параметр призначено для запуску відтворення аудіо під час перебування на сервері. Дана конфігурація є налаштуванням на стороні сервера.

    onion_skin:
        morph_action_color: Відображати попередній морф під час редагування

    immersive_editor:
        model_block: Чи використовувати імерсивний редактор для блоку-моделі
        record_editor: Чи використовувати імерсивний редактор для редактора записів під час використання редактора камери Aperture
