blockbuster.config.comments:
    general:
        show_first_time_modal: Показывать ли заставку первого запуска на главной панели мода
        extra_wubs: А эта штука вообще ничего не делает. А может быть... Тыц?
        auto_refresh_models: Обновить модели и скины при входе в меню Блокбастера и Метаморфа?
        debug_playback_ticks: Записывать тики в лог пока блок режиссёра делает запись
        green_screen_sky: Изменяет цвет неба на выбранный для удобства осуществления хромакеинга
        green_screen_sky_color: Определяет цвет неба для осуществления хромакеинга
        url_skins_sync_download: Синхронная загрузка интернет-ссылок на скины. Если эта настройка включена, то 3D слои будут работать с интернет-скинами, но игра может фризиться чтобы прогрузить скин при добавлении.
        add_utility_blocks: Добавляет такие блоки как командный и структурный на панель Блокбастера в режиме творчества для упрощения процесса получения собственно этих блоков.
        cached_structure_rendering: Включение этой опции сменит метод отображения морфов-структур на менее ресурсозатратный, однако, с ним, блоки из таких модов как Chisel&Bits' станут невидимыми.
        bb_gun_sync_distance: Если значение больше нуля, то будет включена синхронизация снарядов ББ Оружия, тем самым синхронизируя их траекторию с сервером, однако результируя во рванное движение самих снарядов.

    model_block:
        model_block_disable_rendering: Включено ли отображение блоков-моделей
        model_block_disable_item_rendering: Необходимо ли выключить отобржание предметов в руках у блоков-моделей (да кому это надо вообще?)
        restore: Включение этой опции позволяет вернуть старый баг, при котором блоки-модели восстанавливались если их поставить рядом.
        reset_on_playback: Если включено, то при начале воспроизведения все блоки-модели сбросят свои настройки.

    recording:
        recording_countdown: Отсчёт до записи (в секундах)
        record_unload_time: Сколько времени занимает выгрузка записи (в тиках)
        record_unload: Включить автоматическую выгрузку записей?
        record_sync_rate: Насколько часто запись должна синхронизироваться с сервером?
        record_attack_on_swipe: Записывается ли атака вместе с действием взмаха?
        record_commands: Записываются ли команды?
        record_chat_prefix: Префикс который будет добавлен к сообщению о действии в чате (карточка %%NAME%% поддерживается для имени текущего актёра)
        record_pause_preview: Эта опция включает предварительный просмотр анимированных морфов по типу морфов-изображений, анимированных поз, морфов-записей и секвенсерах. Влияет на производительность сервера.

    actor:
        actor_fall_damage: Получают ли актёры урон от падения?
        actor_tracking_range: Насколько далеко отслеживаются актеры? Для вступления изменений в силу необходим перезапуск игры.
        actor_rendering_range: Насколько далеко видны актеры?
        actor_always_render: Отображать актёров всегда, вне зависимости от размера самих актёров или их хитбоксов
        actor_always_render_names: Включить отображение имён актеров?
        actor_swish_swipe: Издают ли актеры звук вжуха когда появляются?
        actor_y: Заставляет актёров использовать правильное значение оси Y (ликвидирует проблему с парением и прыжками, но также делает движение по оси Y резким)
        actor_disable_riding: Отключить возможность взабраться на актёра верхом посредством нажатия правой кнопки мыши
        actor_playback_body_yaw: Необходимо ли проигрывать отдельно записанное горизонтальное вращение тела актёра (этот параметр гарантирует постоянность в воспроизведении вращения, работает только на версиях Блокбастера выше 2.1)

    damage_control:
        damage_control: Включен ли контроль урона?
        damage_control_distance: Радиус эффекта контроля урона

    model_folders:
        path: Абсолютный путь к дополнительной папке моделей (если пользуетесь Windows, добавьте спереди букву, обозначающую жёсткий диск)

    snowstorm:
        depth_sorting: Когда параметр включён, предотвращается видимость частиц за остальными полупрозрачными частицами. Эта опция очень сильно влияет на производительность, рекомендуется включать её только во время вывода видео
    
    audio:
        waveform_visible: Необходимо ли показывать аудиополосе при воспроизведении
        waveform_density: Сколько пикселей должно показываться в аудиополосе за секунду
        waveform_width: Ширина аудиополосы в процентном соотношении плавающей запятой (значение от 0 до 1)
        waveform_height: Высота аудиополосы в пикселях
        waveform_filename: Необходимо ли показывать название проигрываемого аудиофайла
